project_name: firehose-ethereum

release:
  github:
    owner: streamingfast
    name: sf-ethereum
  name_template: '{{.Tag}}'
builds:
  # fireeth
  - id: sf-ethereum
    goos:
    - linux
    - darwin
    goarch:
    - arm64
    - amd64
    targets:
    - linux_amd64
    - darwin_amd64
    - darwin_arm64
    main: ./cmd/fireeth
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: fireeth
    env:
    - CGO_ENABLED=0

  # substreams
  - id: substreams-alpha
    goos:
    - darwin
    goarch:
    - arm64
    - amd64
    targets:
    - darwin_amd64
    - darwin_arm64
    main: ./cmd/substreams-alpha
    binary: substreams-alpha
    env:
      - CGO_ENABLED=1
archives:
  # fireeth
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: sf-ethereum
    builds:
    - sf-ethereum
    replacements:
      amd64: x86_64
      darwin: macOS
      linux: linux
    format: tar.gz
    files:
    - LICENSE
    - README.md

  # substreams
  - name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: substreams-alpha
    builds:
    - substreams-alpha
    replacements:
      amd64: x86_64
      darwin: macOS
    format: tar.gz
    files:
    - LICENSE
    - README.md
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: dist
signs:
- cmd: keybase
  args:
  - sign
  - --infile
  - $artifact
  - --binary
  - --outfile
  - $signature
  - --detached
  signature: ${artifact}.sig
  artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
brews:
  - name: sf-ethereum
    ids:
    - sf-ethereum
    tap:
      owner: streamingfast
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@streamingfast.io
    homepage: "https://github.com/streamingfast/firehose-ethereum"
    description: "Firehose on Ethereum stack"
    license: "Apache-2.0"
